-- Insertar tipos de contenido
INSERT INTO TIPOCONTENIDO (IDTIPOCONTENIDO, DESCTIPOCO) VALUES ('1', 'Imagen');
INSERT INTO TIPOCONTENIDO (IDTIPOCONTENIDO, DESCTIPOCO) VALUES ('2', 'Texto');
INSERT INTO TIPOCONTENIDO (IDTIPOCONTENIDO, DESCTIPOCO) VALUES ('3', 'Emoticons');
INSERT INTO TIPOCONTENIDO (IDTIPOCONTENIDO, DESCTIPOCO) VALUES ('4', 'Url');
INSERT INTO TIPOCONTENIDO (IDTIPOCONTENIDO, DESCTIPOCO) VALUES ('5', 'Video');

-- Insertar tipos de archivo
INSERT INTO TIPOARCHIVO (IDTIPOARCHIVO, DESCTIPOARCHIVO) VALUES ('PDF', 'Documento Portable');
INSERT INTO TIPOARCHIVO (IDTIPOARCHIVO, DESCTIPOARCHIVO) VALUES ('DOC', 'Documento');
INSERT INTO TIPOARCHIVO (IDTIPOARCHIVO, DESCTIPOARCHIVO) VALUES ('XLS', 'Hoja Calculo');
INSERT INTO TIPOARCHIVO (IDTIPOARCHIVO, DESCTIPOARCHIVO) VALUES ('GIF', 'Imagen');
INSERT INTO TIPOARCHIVO (IDTIPOARCHIVO, DESCTIPOARCHIVO) VALUES ('BMP', 'Imagen');
INSERT INTO TIPOARCHIVO (IDTIPOARCHIVO, DESCTIPOARCHIVO) VALUES ('MP4', 'Video');
INSERT INTO TIPOARCHIVO (IDTIPOARCHIVO, DESCTIPOARCHIVO) VALUES ('AVI', 'Video');
INSERT INTO TIPOARCHIVO (IDTIPOARCHIVO, DESCTIPOARCHIVO) VALUES ('MP3', 'Musica');
INSERT INTO TIPOARCHIVO (IDTIPOARCHIVO, DESCTIPOARCHIVO) VALUES ('EXE', 'Ejecutable');


-- Insertar Propiedades
-- =======================
-- Ajustes de cuenta (1)
-- =======================
INSERT INTO PROPIEDAD (IDPROPIEDAD, IDPROPIEDADSUP, DESCPROPIEDAD, VALORDEFECTO, VALORPROPIEDAD)
VALUES ('1', NULL, 'Ajustes de cuenta, Permite gestionar la información de tu perfil, como nombre, foto y descripción.', NULL, NULL);

INSERT INTO PROPIEDAD VALUES ('1.1', '1', 'Verificación en dos pasos: Configura un PIN adicional para mayor seguridad.', 1, NULL);
INSERT INTO PROPIEDAD VALUES ('1.2', '1', 'Bloqueo con huella dactilar: Utiliza tu huella dactilar para bloquear la aplicación.', 1, 'huella');

-- =======================
-- Ajustes de privacidad (2)
-- =======================
INSERT INTO PROPIEDAD VALUES ('2', NULL, 'Ajustes de privacidad: Controla quién puede ver tu hora de última vez, tu estado en línea, foto, info de contacto y quién te puede agregar a grupos.', NULL, NULL);

-- Hora de última vez
INSERT INTO PROPIEDAD VALUES ('2.1', '2', 'Hora de última vez: Selecciona quién puede ver cuándo estuviste en línea.', NULL, NULL);
INSERT INTO PROPIEDAD VALUES ('2.1.1', '2.1', 'Todos', NULL, 'true');
INSERT INTO PROPIEDAD VALUES ('2.1.2', '2.1', 'Mis contactos', NULL, NULL);
INSERT INTO PROPIEDAD VALUES ('2.1.3', '2.1', 'Excepto mis contactos', NULL, NULL);
INSERT INTO PROPIEDAD VALUES ('2.1.4', '2.1', 'Nadie', NULL, NULL);

-- Estado en línea
INSERT INTO PROPIEDAD VALUES ('2.2', '2', 'Estado en línea: Selecciona quién puede ver si estás en línea.', NULL, NULL);
INSERT INTO PROPIEDAD VALUES ('2.2.1', '2.2', 'Todos', NULL, 'true');
INSERT INTO PROPIEDAD VALUES ('2.2.2', '2.2', 'Mis contactos', NULL, NULL);
INSERT INTO PROPIEDAD VALUES ('2.2.3', '2.2', 'Excepto mis contactos', NULL, NULL);
INSERT INTO PROPIEDAD VALUES ('2.2.4', '2.2', 'Nadie', NULL, NULL);

-- Foto de perfil
INSERT INTO PROPIEDAD VALUES ('2.3', '2', 'Foto de perfil: Decide quién puede ver tu foto de perfil.', NULL, NULL);
INSERT INTO PROPIEDAD VALUES ('2.3.1', '2.3', 'Todos', NULL, 'true');
INSERT INTO PROPIEDAD VALUES ('2.3.2', '2.3', 'Mis contactos', NULL, NULL);
INSERT INTO PROPIEDAD VALUES ('2.3.3', '2.3', 'Excepto mis contactos', NULL, NULL);
INSERT INTO PROPIEDAD VALUES ('2.3.4', '2.3', 'Nadie', NULL, NULL);

-- Info
INSERT INTO PROPIEDAD VALUES ('2.4', '2', 'Info: Configura quién puede ver tu descripción.', NULL, NULL);
INSERT INTO PROPIEDAD VALUES ('2.4.1', '2.4', 'Todos', NULL, 'true');
INSERT INTO PROPIEDAD VALUES ('2.4.2', '2.4', 'Mis contactos', NULL, NULL);
INSERT INTO PROPIEDAD VALUES ('2.4.3', '2.4', 'Excepto mis contactos', NULL, NULL);
INSERT INTO PROPIEDAD VALUES ('2.4.4', '2.4', 'Nadie', NULL, NULL);

-- Estado
INSERT INTO PROPIEDAD VALUES ('2.5', '2', 'Estado: Define quién puede ver tus actualizaciones de estado.', NULL, NULL);
INSERT INTO PROPIEDAD VALUES ('2.5.1', '2.5', 'Todos', NULL, 'true');
INSERT INTO PROPIEDAD VALUES ('2.5.2', '2.5', 'Mis contactos', NULL, NULL);
INSERT INTO PROPIEDAD VALUES ('2.5.3', '2.5', 'Excepto mis contactos', NULL, NULL);
INSERT INTO PROPIEDAD VALUES ('2.5.4', '2.5', 'Nadie', NULL, NULL);

-- Confirmaciones de lectura
INSERT INTO PROPIEDAD VALUES ('2.6', '2', 'Confirmaciones de lectura: Decide si quieres que los otros usuarios vean si has leído sus mensajes.', 1, 'true');

-- Grupos
INSERT INTO PROPIEDAD VALUES ('2.7', '2', 'Grupos: Configura quién puede agregarte a grupos.', NULL, NULL);
INSERT INTO PROPIEDAD VALUES ('2.7.1', '2.7', 'Todos', NULL, 'true');
INSERT INTO PROPIEDAD VALUES ('2.7.2', '2.7', 'Mis contactos', NULL, NULL);
INSERT INTO PROPIEDAD VALUES ('2.7.3', '2.7', 'Excepto mis contactos', NULL, NULL);
INSERT INTO PROPIEDAD VALUES ('2.7.4', '2.7', 'Nadie', NULL, NULL);

-- Ubicación en tiempo real
INSERT INTO PROPIEDAD VALUES ('2.8', '2', 'Ubicación en tiempo real: Decide quién puede ver tu ubicación en tiempo real.', NULL, NULL);
INSERT INTO PROPIEDAD VALUES ('2.8.1', '2.8', 'Todos', NULL, 'true');
INSERT INTO PROPIEDAD VALUES ('2.8.2', '2.8', 'Mis contactos', NULL, NULL);
INSERT INTO PROPIEDAD VALUES ('2.8.3', '2.8', 'Excepto mis contactos', NULL, NULL);
INSERT INTO PROPIEDAD VALUES ('2.8.4', '2.8', 'Nadie', NULL, NULL);

-- Ajustes de chat
INSERT INTO PROPIEDAD VALUES ('2.9', '2', 'Ajustes de chat: Permite configurar el fondo del chat, el tamaño de la fuente y otros aspectos visuales.', NULL, NULL);
INSERT INTO PROPIEDAD VALUES ('2.9.1', '2.9', 'Fuente', NULL, 'Arial');
INSERT INTO PROPIEDAD VALUES ('2.9.2', '2.9', 'Tamaño Fuente', NULL, '12');

-- Ajustes de almacenamiento y datos
INSERT INTO PROPIEDAD VALUES ('2.10', '2', 'Ajustes de almacenamiento y datos: Permite gestionar el espacio que ocupa la app y configurar el uso de datos móviles/Wi-Fi.', NULL, NULL);
INSERT INTO PROPIEDAD VALUES ('2.10.1', '2.10', 'Espacio', NULL, '5,40 MB');
INSERT INTO PROPIEDAD VALUES ('2.10.2', '2.10', 'Wi-fi', NULL, 'true');

-- Ajustes de ayuda
INSERT INTO PROPIEDAD VALUES ('2.11', '2', 'Ajustes de ayuda: Permite acceder al centro de ayuda de WhatsApp y a información legal.', 2, 'true');

-- Insertar 10 usuarios
INSERT INTO "USER" (CONSECUSER, CONSECUSERACTUALIZADO, CODUBICA, NOMBRE, APELLIDO, "USER", FECHAREGISTRO, EMAIL, CELULAR) VALUES ('U001', NULL, 'UB01', 'Ana', 'Gómez', 'ana01', SYSDATE, 'ana@example.com', '3000000001');
INSERT INTO "USER" (CONSECUSER, CONSECUSERACTUALIZADO, CODUBICA, NOMBRE, APELLIDO, "USER", FECHAREGISTRO, EMAIL, CELULAR) VALUES ('U002', NULL, 'UB01', 'Luis', 'Martínez', 'luis02', SYSDATE, 'luis@example.com', '3000000002');
INSERT INTO "USER" (CONSECUSER, CONSECUSERACTUALIZADO, CODUBICA, NOMBRE, APELLIDO, "USER", FECHAREGISTRO, EMAIL, CELULAR) VALUES ('U003', NULL, 'UB01', 'María', 'Rojas', 'maria03', SYSDATE, 'maria@example.com', '3000000003');
INSERT INTO "USER" (CONSECUSER, CONSECUSERACTUALIZADO, CODUBICA, NOMBRE, APELLIDO, "USER", FECHAREGISTRO, EMAIL, CELULAR) VALUES ('U004', NULL, 'UB01', 'Pedro', 'Pérez', 'pedro04', SYSDATE, 'pedro@example.com', '3000000004');
INSERT INTO "USER" (CONSECUSER, CONSECUSERACTUALIZADO, CODUBICA, NOMBRE, APELLIDO, "USER", FECHAREGISTRO, EMAIL, CELULAR) VALUES ('U005', NULL, 'UB01', 'Laura', 'Díaz', 'laura05', SYSDATE, 'laura@example.com', '3000000005');
INSERT INTO "USER" (CONSECUSER, CONSECUSERACTUALIZADO, CODUBICA, NOMBRE, APELLIDO, "USER", FECHAREGISTRO, EMAIL, CELULAR) VALUES ('U006', NULL, 'UB01', 'Carlos', 'Jiménez', 'carlos06', SYSDATE, 'carlos@example.com', '3000000006');
INSERT INTO "USER" (CONSECUSER, CONSECUSERACTUALIZADO, CODUBICA, NOMBRE, APELLIDO, "USER", FECHAREGISTRO, EMAIL, CELULAR) VALUES ('U007', NULL, 'UB01', 'Sofía', 'Hernández', 'sofia07', SYSDATE, 'sofia@example.com', '3000000007');
INSERT INTO "USER" (CONSECUSER, CONSECUSERACTUALIZADO, CODUBICA, NOMBRE, APELLIDO, "USER", FECHAREGISTRO, EMAIL, CELULAR) VALUES ('U008', NULL, 'UB01', 'Daniel', 'Gutiérrez', 'daniel08', SYSDATE, 'daniel@example.com', '3000000008');
INSERT INTO "USER" (CONSECUSER, CONSECUSERACTUALIZADO, CODUBICA, NOMBRE, APELLIDO, "USER", FECHAREGISTRO, EMAIL, CELULAR) VALUES ('U009', NULL, 'UB01', 'Paula', 'Torres', 'paula09', SYSDATE, 'paula@example.com', '3000000009');
INSERT INTO "USER" (CONSECUSER, CONSECUSERACTUALIZADO, CODUBICA, NOMBRE, APELLIDO, "USER", FECHAREGISTRO, EMAIL, CELULAR) VALUES ('U010', NULL, 'UB01', 'Miguel', 'Castro', 'miguel10', SYSDATE, 'miguel@example.com', '3000000010');

-- Insertar amistades: cada usuario con 3 amigos
-- Relaciones originales + relaciones inversas para amistad bidireccional
-- U001
INSERT INTO AMIGUSERUSER VALUES ('U001', 'U002');
INSERT INTO AMIGUSERUSER VALUES ('U001', 'U003');
INSERT INTO AMIGUSERUSER VALUES ('U001', 'U004');
INSERT INTO AMIGUSERUSER VALUES ('U002', 'U001');
INSERT INTO AMIGUSERUSER VALUES ('U003', 'U001');
INSERT INTO AMIGUSERUSER VALUES ('U004', 'U001');

-- U002
INSERT INTO AMIGUSERUSER VALUES ('U002', 'U003');
INSERT INTO AMIGUSERUSER VALUES ('U002', 'U004');
INSERT INTO AMIGUSERUSER VALUES ('U002', 'U005');
INSERT INTO AMIGUSERUSER VALUES ('U003', 'U002');
INSERT INTO AMIGUSERUSER VALUES ('U004', 'U002');
INSERT INTO AMIGUSERUSER VALUES ('U005', 'U002');

-- U003
INSERT INTO AMIGUSERUSER VALUES ('U003', 'U004');
INSERT INTO AMIGUSERUSER VALUES ('U003', 'U005');
INSERT INTO AMIGUSERUSER VALUES ('U003', 'U006');
INSERT INTO AMIGUSERUSER VALUES ('U004', 'U003');
INSERT INTO AMIGUSERUSER VALUES ('U005', 'U003');
INSERT INTO AMIGUSERUSER VALUES ('U006', 'U003');

-- U004
INSERT INTO AMIGUSERUSER VALUES ('U004', 'U005');
INSERT INTO AMIGUSERUSER VALUES ('U004', 'U006');
INSERT INTO AMIGUSERUSER VALUES ('U004', 'U007');
INSERT INTO AMIGUSERUSER VALUES ('U005', 'U004');
INSERT INTO AMIGUSERUSER VALUES ('U006', 'U004');
INSERT INTO AMIGUSERUSER VALUES ('U007', 'U004');

-- U005
INSERT INTO AMIGUSERUSER VALUES ('U005', 'U006');
INSERT INTO AMIGUSERUSER VALUES ('U005', 'U007');
INSERT INTO AMIGUSERUSER VALUES ('U005', 'U008');
INSERT INTO AMIGUSERUSER VALUES ('U006', 'U005');
INSERT INTO AMIGUSERUSER VALUES ('U007', 'U005');
INSERT INTO AMIGUSERUSER VALUES ('U008', 'U005');

-- U006
INSERT INTO AMIGUSERUSER VALUES ('U006', 'U007');
INSERT INTO AMIGUSERUSER VALUES ('U006', 'U008');
INSERT INTO AMIGUSERUSER VALUES ('U006', 'U009');
INSERT INTO AMIGUSERUSER VALUES ('U007', 'U006');
INSERT INTO AMIGUSERUSER VALUES ('U008', 'U006');
INSERT INTO AMIGUSERUSER VALUES ('U009', 'U006');

-- U007
INSERT INTO AMIGUSERUSER VALUES ('U007', 'U008');
INSERT INTO AMIGUSERUSER VALUES ('U007', 'U009');
INSERT INTO AMIGUSERUSER VALUES ('U007', 'U010');
INSERT INTO AMIGUSERUSER VALUES ('U008', 'U007');
INSERT INTO AMIGUSERUSER VALUES ('U009', 'U007');
INSERT INTO AMIGUSERUSER VALUES ('U010', 'U007');

-- U008
INSERT INTO AMIGUSERUSER VALUES ('U008', 'U009');
INSERT INTO AMIGUSERUSER VALUES ('U008', 'U010');
INSERT INTO AMIGUSERUSER VALUES ('U008', 'U001');
INSERT INTO AMIGUSERUSER VALUES ('U009', 'U008');
INSERT INTO AMIGUSERUSER VALUES ('U010', 'U008');
INSERT INTO AMIGUSERUSER VALUES ('U001', 'U008');

-- U009
INSERT INTO AMIGUSERUSER VALUES ('U009', 'U010');
INSERT INTO AMIGUSERUSER VALUES ('U009', 'U001');
INSERT INTO AMIGUSERUSER VALUES ('U009', 'U002');
INSERT INTO AMIGUSERUSER VALUES ('U010', 'U009');
INSERT INTO AMIGUSERUSER VALUES ('U001', 'U009');
INSERT INTO AMIGUSERUSER VALUES ('U002', 'U009');

-- U010
INSERT INTO AMIGUSERUSER VALUES ('U010', 'U001');
INSERT INTO AMIGUSERUSER VALUES ('U010', 'U002');
INSERT INTO AMIGUSERUSER VALUES ('U010', 'U003');
INSERT INTO AMIGUSERUSER VALUES ('U001', 'U010');
INSERT INTO AMIGUSERUSER VALUES ('U002', 'U010');
INSERT INTO AMIGUSERUSER VALUES ('U003', 'U010');

-- Insertar 3 grupos con administradores U001, U002 y U003
INSERT INTO GRUPO (CODGRUPO, CONSECUSERADMIN, NOMGRUPO, FECHAREGGRUPO, IMAGGRUPO)
VALUES (1, 'U001', 'Grupo Alpha', SYSDATE, NULL);

INSERT INTO GRUPO (CODGRUPO, CONSECUSERADMIN, NOMGRUPO, FECHAREGGRUPO, IMAGGRUPO)
VALUES (2, 'U002', 'Grupo Beta', SYSDATE, NULL);

INSERT INTO GRUPO (CODGRUPO, CONSECUSERADMIN, NOMGRUPO, FECHAREGGRUPO, IMAGGRUPO)
VALUES (3, 'U003', 'Grupo Gamma', SYSDATE, NULL);

-- Grupo 1: U001-U006
INSERT INTO PERTENECEUSERGRUPO VALUES (1, 'U001');
INSERT INTO PERTENECEUSERGRUPO VALUES (1, 'U002');
INSERT INTO PERTENECEUSERGRUPO VALUES (1, 'U003');
INSERT INTO PERTENECEUSERGRUPO VALUES (1, 'U004');
INSERT INTO PERTENECEUSERGRUPO VALUES (1, 'U005');
INSERT INTO PERTENECEUSERGRUPO VALUES (1, 'U006');

-- Grupo 2: U003-U008
INSERT INTO PERTENECEUSERGRUPO VALUES (2, 'U003');
INSERT INTO PERTENECEUSERGRUPO VALUES (2, 'U004');
INSERT INTO PERTENECEUSERGRUPO VALUES (2, 'U005');
INSERT INTO PERTENECEUSERGRUPO VALUES (2, 'U006');
INSERT INTO PERTENECEUSERGRUPO VALUES (2, 'U007');
INSERT INTO PERTENECEUSERGRUPO VALUES (2, 'U008');

-- Grupo 3: U005-U010
INSERT INTO PERTENECEUSERGRUPO VALUES (3, 'U005');
INSERT INTO PERTENECEUSERGRUPO VALUES (3, 'U006');
INSERT INTO PERTENECEUSERGRUPO VALUES (3, 'U007');
INSERT INTO PERTENECEUSERGRUPO VALUES (3, 'U008');
INSERT INTO PERTENECEUSERGRUPO VALUES (3, 'U009');
INSERT INTO PERTENECEUSERGRUPO VALUES (3, 'U010');

-- =================================
-- Grupo 1 (CODGRUPO=1) - admin U001
-- =================================

-- Mensaje principal del hilo
INSERT INTO MENSAJE (CONSECUSERRECIBE, CONSECUSERENVIA, CONSMESAJE, CODGRUPO, FECHAREGMEN)
VALUES ('U001', 'U002', 1, 1, SYSDATE);

-- Dos mensajes fuera del hilo
INSERT INTO MENSAJE VALUES ('U001', 'U003', 2, 1, NULL, NULL, NULL, SYSDATE);
INSERT INTO MENSAJE VALUES ('U001', 'U004', 3, 1, NULL, NULL, NULL, SYSDATE);

-- Mensajes que responden al mensaje 1
INSERT INTO MENSAJE VALUES ('U001', 'U005', 4, 1, 'U001', 'U002', 1, SYSDATE);
INSERT INTO MENSAJE VALUES ('U001', 'U006', 5, 1, 'U001', 'U002', 1, SYSDATE);
INSERT INTO MENSAJE VALUES ('U001', 'U002', 6, 1, 'U001', 'U002', 1, SYSDATE);

-- Mensajes adicionales normales
INSERT INTO MENSAJE VALUES ('U001', 'U002', 7, 1, NULL, NULL, NULL, SYSDATE);
INSERT INTO MENSAJE VALUES ('U001', 'U003', 8, 1, NULL, NULL, NULL, SYSDATE);
INSERT INTO MENSAJE VALUES ('U001', 'U004', 9, 1, NULL, NULL, NULL, SYSDATE);
INSERT INTO MENSAJE VALUES ('U001', 'U005', 10, 1, NULL, NULL, NULL, SYSDATE);

-- Contenido para mensaje 2 (imagen)
INSERT INTO CONTENIDO (CONSECUSERRECIBE, CONSECUSERENVIA, CONSMESAJE, CONSECONTENIDO, IDTIPOCONTENIDO, IDTIPOARCHIVO, CONTENIDOIMAG, LOCALIZACONTENIDO)
VALUES ('U001', 'U003', 2, 1, '1', 'GIF', EMPTY_BLOB(), 'ruta/imagen1.gif');

-- Contenido para mensaje 7 (archivo)
INSERT INTO CONTENIDO VALUES ('U001', 'U002', 7, 1, '2', 'PDF', EMPTY_BLOB(), 'ruta/documento1.pdf');

-- =================================
-- Grupo 2 (CODGRUPO=2) - admin U002
-- =================================

INSERT INTO MENSAJE VALUES ('U002', 'U003', 1, 2, NULL, NULL, NULL, SYSDATE);
INSERT INTO MENSAJE VALUES ('U002', 'U004', 2, 2, NULL, NULL, NULL, SYSDATE);
INSERT INTO MENSAJE VALUES ('U002', 'U005', 3, 2, NULL, NULL, NULL, SYSDATE);

INSERT INTO MENSAJE VALUES ('U002', 'U006', 4, 2, 'U002', 'U003', 1, SYSDATE);
INSERT INTO MENSAJE VALUES ('U002', 'U007', 5, 2, 'U002', 'U003', 1, SYSDATE);
INSERT INTO MENSAJE VALUES ('U002', 'U008', 6, 2, 'U002', 'U003', 1, SYSDATE);

INSERT INTO MENSAJE VALUES ('U002', 'U003', 7, 2, NULL, NULL, NULL, SYSDATE);
INSERT INTO MENSAJE VALUES ('U002', 'U004', 8, 2, NULL, NULL, NULL, SYSDATE);
INSERT INTO MENSAJE VALUES ('U002', 'U005', 9, 2, NULL, NULL, NULL, SYSDATE);
INSERT INTO MENSAJE VALUES ('U002', 'U006', 10, 2, NULL, NULL, NULL, SYSDATE);

INSERT INTO CONTENIDO VALUES ('U002', 'U004', 2, 1, '1', 'BMP', EMPTY_BLOB(), 'ruta/imagen2.bmp');
INSERT INTO CONTENIDO VALUES ('U002', 'U003', 7, 1, '2', 'MP4', EMPTY_BLOB(), 'ruta/video1.mp4');

-- =================================
-- Grupo 3 (CODGRUPO=3) - admin U003
-- =================================

INSERT INTO MENSAJE VALUES ('U003', 'U005', 1, 3, NULL, NULL, NULL, SYSDATE);
INSERT INTO MENSAJE VALUES ('U003', 'U006', 2, 3, NULL, NULL, NULL, SYSDATE);
INSERT INTO MENSAJE VALUES ('U003', 'U007', 3, 3, NULL, NULL, NULL, SYSDATE);

INSERT INTO MENSAJE VALUES ('U003', 'U008', 4, 3, 'U003', 'U005', 1, SYSDATE);
INSERT INTO MENSAJE VALUES ('U003', 'U009', 5, 3, 'U003', 'U005', 1, SYSDATE);
INSERT INTO MENSAJE VALUES ('U003', 'U010', 6, 3, 'U003', 'U005', 1, SYSDATE);

INSERT INTO MENSAJE VALUES ('U003', 'U005', 7, 3, NULL, NULL, NULL, SYSDATE);
INSERT INTO MENSAJE VALUES ('U003', 'U006', 8, 3, NULL, NULL, NULL, SYSDATE);
INSERT INTO MENSAJE VALUES ('U003', 'U007', 9, 3, NULL, NULL, NULL, SYSDATE);
INSERT INTO MENSAJE VALUES ('U003', 'U008', 10, 3, NULL, NULL, NULL, SYSDATE);

INSERT INTO CONTENIDO VALUES ('U003', 'U006', 2, 1, '1', 'GIF', EMPTY_BLOB(), 'ruta/imagen3.gif');
INSERT INTO CONTENIDO VALUES ('U003', 'U005', 7, 1, '2', 'DOC', EMPTY_BLOB(), 'ruta/documento2.doc');
